// Package config defines the KnotOS configuration schema and provides
// loading, saving, and validation. The schema is intentionally minimal in
// M2 — it grows in M3 (snapshots), M4 (auth), and M5 (network roles).
package config

// Role identifies what KnotOS is currently doing on the network. The set of
// available roles depends on detected hardware capabilities (see internal/role).
type Role string

const (
	// RoleSetup is a transient role used for the first-run wizard: an open
	// Wi-Fi AP without uplink, only for onboarding.
	RoleSetup Role = "setup"

	// RoleWiFiExtender connects wlan0 to an upstream Wi-Fi network and
	// re-broadcasts a separate SSID via ap0, NATting between them. This is
	// the primary v0.1 role on a Pi Zero 2W with no Ethernet dongle.
	RoleWiFiExtender Role = "wifi-extender"

	// RoleWiFiRouter is full-router mode added in v0.3: a USB-Ethernet
	// adapter is the WAN, wlan0 is a dedicated AP (no STA), the user
	// picks the AP channel directly. Available wherever the capability
	// probe finds a USB-Eth netdev — Zero 2W and Pi 4/5 alike.
	RoleWiFiRouter Role = "wifi-router"
)

// Config is the root configuration document, persisted as YAML at
// /etc/knot/config.yaml.
type Config struct {
	Device  Device                  `yaml:"device"            json:"device"`
	Role    Role                    `yaml:"role"              json:"role"`
	Auth    Auth                    `yaml:"auth"              json:"auth"`
	Network Network                 `yaml:"network"           json:"network"`
	Plugins map[string]PluginConfig `yaml:"plugins,omitempty" json:"plugins,omitempty"`
}

// Auth holds credentials for the local admin account.
//
// PasswordHash is the bcrypt hash of the admin password. It is stored
// in YAML (never the plaintext) and exposed over the API only as a
// boolean "configured" flag — never the hash itself.
type Auth struct {
	PasswordHash string `yaml:"password_hash,omitempty" json:"-"`
}

// Device holds top-level identity and locale settings.
type Device struct {
	// Name is the human-readable hostname (also used for mDNS).
	Name string `yaml:"name" json:"name"`
	// Country is the ISO 3166-1 alpha-2 regulatory domain (e.g. "RU", "US").
	// Required for Wi-Fi to come up at full power on legal channels.
	Country string `yaml:"country" json:"country"`
}

// Network groups all networking-related settings.
type Network struct {
	// Uplink describes the Wi-Fi STA connection (wlan0). Empty when the
	// role is "setup" or "wifi-router".
	Uplink *WiFiUplink `yaml:"uplink,omitempty" json:"uplink,omitempty"`
	// AP describes the broadcasted Wi-Fi network (ap0 in extender,
	// wlan0 in router). Empty when the role does not broadcast.
	AP *WiFiAP `yaml:"ap,omitempty" json:"ap,omitempty"`
	// LAN describes the IPv4 subnet served to AP clients.
	LAN *LAN `yaml:"lan,omitempty" json:"lan,omitempty"`
	// WAN is the upstream interface for the wifi-router role.
	// Empty in setup and extender roles.
	WAN *WAN `yaml:"wan,omitempty" json:"wan,omitempty"`
	// DNS controls how the resolver forwards queries upstream.
	// Empty/nil keeps the v0.3 default of plain UDP to 1.1.1.1 +
	// 8.8.8.8.
	DNS *DNSUpstream `yaml:"dns,omitempty" json:"dns,omitempty"`
	// PortForwards maps inbound WAN ports to LAN devices. Only
	// honoured in the wifi-router role (the extender has no WAN of
	// its own). Empty == none.
	PortForwards []PortForward `yaml:"port_forwards,omitempty" json:"port_forwards,omitempty"`
	// Zapret configures the DPI-bypass engine (nfqws) used to reach
	// YouTube/Discord through ISP throttling. Nil/disabled == off.
	Zapret *Zapret `yaml:"zapret,omitempty" json:"zapret,omitempty"`
}

// Zapret holds the DPI-circumvention (nfqws) settings. The actual
// desync strategy and domain lists live on disk under the zapret
// runtime dir and are updatable independently of the knotd binary;
// this struct only carries the user's on/off + strategy selection.
type Zapret struct {
	// Enabled turns the nfqws engine + its nftables NFQUEUE hook on.
	Enabled bool `yaml:"enabled" json:"enabled"`
	// Strategy is the ID of a built-in preset ("general", "alt", …).
	// Ignored when CustomArgs is set.
	Strategy string `yaml:"strategy,omitempty" json:"strategy,omitempty"`
	// CustomArgs, when non-empty, replaces the preset entirely: it is
	// the raw nfqws argument string (e.g. pasted from a Flowseal
	// strategy). Lets the user change strategy without a new binary.
	CustomArgs string `yaml:"custom_args,omitempty" json:"custom_args,omitempty"`
}

// PortForward is a single inbound DNAT rule: traffic arriving on the
// WAN interface at WANPort is rewritten to DestIP:DestPort on the LAN.
type PortForward struct {
	// ID is a stable, URL-safe identifier (used by the API to address
	// a single rule). Generated by the server when empty.
	ID string `yaml:"id" json:"id"`
	// Description is a short human label ("Game server", "NAS").
	Description string `yaml:"description,omitempty" json:"description,omitempty"`
	// Proto is "tcp", "udp", or "tcp/udp".
	Proto string `yaml:"proto" json:"proto"`
	// WANPort is the externally-visible port packets arrive on.
	WANPort int `yaml:"wan_port" json:"wan_port"`
	// DestIP is the LAN device the traffic is forwarded to.
	DestIP string `yaml:"dest_ip" json:"dest_ip"`
	// DestPort is the port on the LAN device. 0 means "same as WANPort".
	DestPort int `yaml:"dest_port,omitempty" json:"dest_port,omitempty"`
	// Enabled toggles the rule without deleting it.
	Enabled bool `yaml:"enabled" json:"enabled"`
}

// EffectiveDestPort returns DestPort, defaulting to WANPort when unset.
func (p PortForward) EffectiveDestPort() int {
	if p.DestPort == 0 {
		return p.WANPort
	}
	return p.DestPort
}

// DNSUpstream picks the wire transport for upstream DNS plus an
// optional override list.
type DNSUpstream struct {
	// Mode is "udp" (default) or "doh". Empty == "udp".
	Mode string `yaml:"mode,omitempty" json:"mode,omitempty"`
	// Upstreams is an optional override; empty means "use the
	// built-in defaults for the chosen mode" (Cloudflare + Google
	// for UDP, Cloudflare + Quad9 for DoH).
	Upstreams []string `yaml:"upstreams,omitempty" json:"upstreams,omitempty"`
}

// WiFiUplink is the configuration of the upstream Wi-Fi connection.
type WiFiUplink struct {
	SSID string `yaml:"ssid" json:"ssid"`
	// PSK is the WPA2 passphrase. Empty for open networks.
	//
	// v0.1 stores this as plaintext in /etc/knot/config.yaml; the file
	// is owned by root with 0600 permissions. A future change will
	// encrypt PSKs at rest with a per-device key derived at first
	// boot — when that lands, the YAML field will be renamed to
	// `psk_encrypted` and a migration runs once.
	PSK string `yaml:"psk,omitempty" json:"psk,omitempty"`
}

// WiFiAP is the configuration of the broadcasted Wi-Fi network.
//
// The channel is intentionally not configurable on Zero 2W: when AP and STA
// share a single radio (BCM43436), the kernel forces them onto the same
// channel as the uplink. The UI surfaces this constraint to the user.
type WiFiAP struct {
	SSID string `yaml:"ssid"                    json:"ssid"`
	PSK  string `yaml:"psk,omitempty" json:"psk,omitempty"`
	// Band is "2.4" or "5". On Zero 2W only 2.4 is supported reliably for ap0.
	Band string `yaml:"band" json:"band"`
	// Channel is the explicit AP channel. Honoured in wifi-router
	// mode (AP runs alone on the radio so the user picks freely);
	// ignored in wifi-extender (kernel forces same-channel as STA).
	// 0 means "let hostapd / driver choose".
	Channel int `yaml:"channel,omitempty" json:"channel,omitempty"`
}

// WAN describes the upstream for the wifi-router role.
//
// Modes:
//   - "dhcp" (default): knotd runs a DHCP client on Interface (an
//     Ethernet WAN) and uses whatever the upstream hands out.
//   - "modem": the WAN is a USB cellular modem. Interface is resolved
//     dynamically (the modem's data netdev, e.g. wwan0) after knotd
//     connects it via ModemManager; the Modem block carries APN/PIN.
type WAN struct {
	// Interface is the kernel netdev name (e.g. "eth0"). Resolved
	// at apply-time from the capability probe; the wizard surfaces
	// the friendly model name but stores the kernel name here so
	// future udev re-naming doesn't silently break the role. May be
	// empty in "modem" mode (the data interface is discovered).
	Interface string `yaml:"interface" json:"interface"`
	// Mode is "dhcp" (default) or "modem".
	Mode string `yaml:"mode,omitempty" json:"mode,omitempty"`
	// Modem holds cellular settings, used only when Mode == "modem".
	Modem *Modem `yaml:"modem,omitempty" json:"modem,omitempty"`
}

// Modem configures a USB cellular (LTE/4G) WAN driven via ModemManager.
// Most carriers auto-provision, so APN is often the only field needed;
// some require a PIN or a user/password pair.
type Modem struct {
	// APN is the carrier access point name (e.g. "internet"). Empty
	// lets ModemManager try the carrier default.
	APN string `yaml:"apn,omitempty" json:"apn,omitempty"`
	// PIN unlocks the SIM when it's PIN-locked. Empty == no PIN.
	PIN string `yaml:"pin,omitempty" json:"pin,omitempty"`
	// Username / Password for the rare carriers that require PAP/CHAP.
	Username string `yaml:"username,omitempty" json:"username,omitempty"`
	Password string `yaml:"password,omitempty" json:"password,omitempty"`
	// SIMSlot selects the active SIM slot (1-based) on modems that expose
	// more than one. 0 leaves ModemManager's current primary slot as-is —
	// the right default for the common single-SIM modem. Inert on modems
	// that report a single slot.
	SIMSlot int `yaml:"sim_slot,omitempty" json:"sim_slot,omitempty"`
}

// LAN is the IPv4 subnet config for the AP side.
type LAN struct {
	// CIDR is the network in CIDR form (e.g. "192.168.42.0/24").
	CIDR string `yaml:"cidr" json:"cidr"`
	DHCP DHCP   `yaml:"dhcp" json:"dhcp"`
}

// DHCP holds the address pool for the LAN's DHCP server.
type DHCP struct {
	PoolStart string `yaml:"pool_start" json:"pool_start"`
	PoolEnd   string `yaml:"pool_end"   json:"pool_end"`
}

// PluginConfig is per-plugin runtime state stored in the central config.
// Plugin-specific fields live in the plugin's own datastore — only the
// enable flag is part of the global config.
type PluginConfig struct {
	Enabled bool `yaml:"enabled" json:"enabled"`
}

// Default returns the configuration knotd uses on first boot, before the
// setup wizard has run. The role is "setup", which surfaces an open AP and
// the captive-portal wizard.
func Default() Config {
	return Config{
		Device: Device{
			Name:    "knot",
			Country: "00", // 00 = global, conservative regdomain
		},
		Role: RoleSetup,
		Network: Network{
			LAN: &LAN{
				CIDR: "192.168.42.0/24",
				DHCP: DHCP{
					PoolStart: "192.168.42.100",
					PoolEnd:   "192.168.42.200",
				},
			},
		},
	}
}
