package vpn

import (
	"fmt"
	"strings"
)

// RenderServerConf produces the wg-quick-format config that lives
// at /etc/wireguard/wg0.conf. Includes:
//
//   - [Interface] block: server private key, the wg0 address with
//     prefix length (/24 typically), the listen port.
//   - One [Peer] block per registered peer with PublicKey and
//     AllowedIPs = <peer-ip>/32. AllowedIPs is what the kernel uses
//     to decide which peer a given inbound packet belongs to;
//     restricting to the /32 prevents one peer from spoofing another.
//
// We do NOT add `PostUp` / `PostDown` hooks here — the NAT and
// forward rules are owned by core/internal/network/linux/* and
// applied centrally with the rest of the firewall on every Apply.
// Mixing wg-quick's own hook system with our nftables would lead
// to ordering bugs.
func RenderServerConf(s ServerConfig, peers []Peer) string {
	var b strings.Builder

	fmt.Fprintln(&b, "# generated by knotd — do not edit by hand")
	fmt.Fprintln(&b, "[Interface]")
	fmt.Fprintf(&b, "PrivateKey = %s\n", s.PrivateKey.String())
	fmt.Fprintf(&b, "Address = %s\n", s.InterfaceCIDR)
	fmt.Fprintf(&b, "ListenPort = %d\n", s.ListenPort)
	// SaveConfig is deliberately off: knotd is the source of truth,
	// any out-of-band `wg set` should not get flushed back to our
	// YAML on shutdown.
	fmt.Fprintln(&b, "SaveConfig = false")

	for _, p := range peers {
		fmt.Fprintln(&b)
		fmt.Fprintf(&b, "# peer: %s (%s)\n", p.Name, p.ID)
		fmt.Fprintln(&b, "[Peer]")
		fmt.Fprintf(&b, "PublicKey = %s\n", p.PublicKey.String())
		fmt.Fprintf(&b, "AllowedIPs = %s\n", p.AllowedIP)
	}
	return b.String()
}

// ClientConfigOptions covers the per-client knobs the user picks
// in the UI when adding a peer.
type ClientConfigOptions struct {
	// FullTunnel routes ALL of the client's traffic through the
	// home VPN. False uses split-tunnel — only the LAN subnet plus
	// the WG subnet itself are pushed.
	FullTunnel bool
	// LANRouteCIDR is the LAN subnet behind knotd that the client
	// should be able to reach (e.g. "192.168.42.0/24"). Non-empty
	// even when FullTunnel=false; we always want the LAN reachable.
	LANRouteCIDR string
	// DNSAddress is the IP the client should use as DNS while the
	// tunnel is up. Almost always the LAN gateway IP, so per-peer
	// ad-block + query log work the same as on the LAN.
	DNSAddress string
}

// RenderClientConf produces the wg-quick config for a single peer,
// rendered exactly once at peer-creation time and either shown to
// the user as text + QR or downloaded as a .conf file. After the
// user closes the dialog, knotd no longer holds the peer's private
// key — it lives only in the user's WireGuard app.
func RenderClientConf(s ServerConfig, serverPub Key, peer Peer, peerPriv Key, opts ClientConfigOptions) string {
	var b strings.Builder

	allowed := splitTunnelAllowed(s.InterfaceCIDR, opts)
	if opts.FullTunnel {
		allowed = "0.0.0.0/0, ::/0"
	}

	fmt.Fprintln(&b, "[Interface]")
	fmt.Fprintf(&b, "PrivateKey = %s\n", peerPriv.String())
	fmt.Fprintf(&b, "Address = %s\n", peer.AllowedIP)
	if opts.DNSAddress != "" {
		fmt.Fprintf(&b, "DNS = %s\n", opts.DNSAddress)
	}

	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "[Peer]")
	fmt.Fprintf(&b, "PublicKey = %s\n", serverPub.String())
	fmt.Fprintf(&b, "AllowedIPs = %s\n", allowed)
	if s.EndpointHost != "" {
		fmt.Fprintf(&b, "Endpoint = %s:%d\n", s.EndpointHost, s.ListenPort)
	}
	// 25s keepalive is the standard advice for keeping NATs open
	// without burning battery. WireGuard doc recommends it whenever
	// the client is behind NAT, which on cellular is always.
	fmt.Fprintln(&b, "PersistentKeepalive = 25")

	return b.String()
}

// splitTunnelAllowed builds the AllowedIPs list for a split-tunnel
// client: the WG subnet itself plus the LAN. Concatenated with a
// comma so wg-quick parses it as a multi-CIDR field.
func splitTunnelAllowed(serverCIDR string, opts ClientConfigOptions) string {
	parts := []string{serverCIDR}
	if opts.LANRouteCIDR != "" && opts.LANRouteCIDR != serverCIDR {
		parts = append(parts, opts.LANRouteCIDR)
	}
	return strings.Join(parts, ", ")
}
