package linux

import (
	"fmt"
	"strings"

	"github.com/knot-os/knot-os/core/internal/config"
)

// SetupSSIDPrefix is prepended to the last 4 hex chars of the device's
// MAC to form the open onboarding SSID, e.g. "KnotOS-setup-A1B2".
const SetupSSIDPrefix = "KnotOS-setup-"

// HostapdParams is the input to BuildHostapdConf. The default channel
// value of 0 leaves hostapd to pick — for setup mode that is fine, but
// for wifi-extender mode the orchestrator must populate it with the
// STA's current channel before writing the file (driver constraint).
type HostapdParams struct {
	Interface string
	SSID      string
	Country   string
	Channel   int    // 1-13 for 2.4 GHz; 0 = let hostapd choose
	Band      string // "2.4" only for v0.1; "5" deferred
	PSK       string // empty = open network
}

// BuildHostapdConf returns the contents of /run/knot/hostapd.conf for
// the given parameters. The output is a deterministic string with no
// trailing whitespace, suitable for direct comparison in tests.
func BuildHostapdConf(p HostapdParams) string {
	if p.Channel == 0 {
		p.Channel = 6
	}
	if p.Country == "" {
		p.Country = "00"
	}

	var b strings.Builder
	fmt.Fprintln(&b, "# generated by knotd — do not edit by hand")
	fmt.Fprintf(&b, "interface=%s\n", p.Interface)
	fmt.Fprintln(&b, "driver=nl80211")
	fmt.Fprintf(&b, "ssid=%s\n", p.SSID)
	fmt.Fprintf(&b, "country_code=%s\n", p.Country)
	fmt.Fprintln(&b, "ieee80211d=1")

	// Only 2.4 GHz on Zero 2W ap0 in v0.1.
	fmt.Fprintln(&b, "hw_mode=g")
	fmt.Fprintf(&b, "channel=%d\n", p.Channel)
	fmt.Fprintln(&b, "ieee80211n=1")

	fmt.Fprintln(&b, "auth_algs=1")
	fmt.Fprintln(&b, "wmm_enabled=1")
	fmt.Fprintln(&b, "ignore_broadcast_ssid=0")

	if p.PSK == "" {
		// Open network: hostapd needs no wpa_* directives.
		return b.String()
	}
	fmt.Fprintln(&b, "wpa=2")
	fmt.Fprintln(&b, "wpa_key_mgmt=WPA-PSK")
	fmt.Fprintln(&b, "rsn_pairwise=CCMP")
	fmt.Fprintf(&b, "wpa_passphrase=%s\n", p.PSK)
	return b.String()
}

// WpaSupplicantParams is the input for BuildWpaSupplicantConf.
type WpaSupplicantParams struct {
	Country string
	SSID    string
	PSK     string // empty = open network
}

// BuildWpaSupplicantConf returns wpa_supplicant.conf for the upstream
// connection on wlan0. Used only by the wifi-extender role.
func BuildWpaSupplicantConf(p WpaSupplicantParams) string {
	if p.Country == "" {
		p.Country = "00"
	}

	var b strings.Builder
	fmt.Fprintln(&b, "# generated by knotd — do not edit by hand")
	fmt.Fprintln(&b, "ctrl_interface=DIR=/run/wpa_supplicant GROUP=netdev")
	fmt.Fprintln(&b, "update_config=0")
	fmt.Fprintf(&b, "country=%s\n", p.Country)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "network={")
	fmt.Fprintf(&b, "    ssid=%q\n", p.SSID)
	fmt.Fprintln(&b, "    scan_ssid=1")
	if p.PSK == "" {
		fmt.Fprintln(&b, "    key_mgmt=NONE")
	} else {
		fmt.Fprintln(&b, "    key_mgmt=WPA-PSK")
		fmt.Fprintf(&b, "    psk=%q\n", p.PSK)
	}
	fmt.Fprintln(&b, "}")
	return b.String()
}

// DnsmasqParams is the input for BuildDnsmasqConf.
type DnsmasqParams struct {
	// Interface is the LAN side (ap0) — dnsmasq binds here.
	Interface string
	// ListenIP is the address dnsmasq serves on (the LAN gateway).
	ListenIP      string
	DHCPPoolStart string
	DHCPPoolEnd   string
	// CaptivePortal redirects every DNS query to ListenIP. Used in
	// setup role so the wizard opens automatically when a phone
	// connects.
	CaptivePortal bool
	// Forwarders is the list of upstream DNS servers (used in
	// wifi-extender role). Ignored when CaptivePortal is set.
	Forwarders []string
}

// BuildDnsmasqConf returns dnsmasq.conf for the given parameters.
func BuildDnsmasqConf(p DnsmasqParams) string {
	var b strings.Builder
	fmt.Fprintln(&b, "# generated by knotd — do not edit by hand")
	fmt.Fprintf(&b, "interface=%s\n", p.Interface)
	fmt.Fprintln(&b, "bind-interfaces")
	fmt.Fprintf(&b, "listen-address=%s\n", p.ListenIP)
	fmt.Fprintln(&b, "no-resolv")
	fmt.Fprintln(&b, "no-poll")
	fmt.Fprintf(&b, "dhcp-range=%s,%s,12h\n", p.DHCPPoolStart, p.DHCPPoolEnd)
	fmt.Fprintf(&b, "dhcp-option=option:router,%s\n", p.ListenIP)
	fmt.Fprintf(&b, "dhcp-option=option:dns-server,%s\n", p.ListenIP)

	if p.CaptivePortal {
		fmt.Fprintln(&b)
		fmt.Fprintln(&b, "# captive portal — every DNS query resolves to the gateway")
		fmt.Fprintf(&b, "address=/#/%s\n", p.ListenIP)
		return b.String()
	}

	fmt.Fprintln(&b)
	for _, fwd := range p.Forwarders {
		fmt.Fprintf(&b, "server=%s\n", fwd)
	}
	return b.String()
}

// NftablesParams is the input for BuildNftables. Only used in
// wifi-extender role; setup uses the captive-portal variant below.
type NftablesParams struct {
	WANInterface string // wlan0
	LANInterface string // ap0
	LANCIDR      string // e.g. 192.168.42.0/24
}

// BuildNftablesExtender returns the nftables ruleset for the
// wifi-extender role: NAT from LAN to WAN, accept forwarded traffic.
func BuildNftablesExtender(p NftablesParams) string {
	return fmt.Sprintf(`# generated by knotd — do not edit by hand
table inet knot {
    chain forward {
        type filter hook forward priority filter; policy drop;
        iifname "%[2]s" oifname "%[1]s" accept;
        iifname "%[1]s" oifname "%[2]s" ct state established,related accept;
    }
}

table ip knot_nat {
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        ip saddr %[3]s oifname "%[1]s" masquerade;
    }
}
`, p.WANInterface, p.LANInterface, p.LANCIDR)
}

// CaptivePortalParams is the input for BuildNftablesCaptive.
type CaptivePortalParams struct {
	LANInterface string
	GatewayIP    string
	HTTPPort     int // knotd's HTTP port
}

// BuildNftablesCaptive returns the nftables ruleset used in setup
// role: every HTTP request from the LAN is redirected to knotd so the
// wizard appears automatically.
func BuildNftablesCaptive(p CaptivePortalParams) string {
	return fmt.Sprintf(`# generated by knotd — do not edit by hand
table ip knot_captive {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
        iifname "%[1]s" tcp dport 80 dnat to %[2]s:%[3]d;
        iifname "%[1]s" tcp dport 443 dnat to %[2]s:%[3]d;
    }
}
`, p.LANInterface, p.GatewayIP, p.HTTPPort)
}

// DefaultLAN returns the LAN block knotd uses on first boot. Mirrors
// config.Default() — the two should never disagree.
func DefaultLAN() *config.LAN {
	return &config.LAN{
		CIDR: "192.168.42.0/24",
		DHCP: config.DHCP{
			PoolStart: "192.168.42.100",
			PoolEnd:   "192.168.42.200",
		},
	}
}

// SetupSSID returns the deterministic open-AP SSID for setup mode,
// derived from the MAC address. mac is expected as colon-separated hex
// (e.g. "dc:a6:32:11:22:33"); the function is forgiving on case and
// length and falls back to "0000" if it cannot extract 4 hex chars.
func SetupSSID(mac string) string {
	clean := strings.ReplaceAll(mac, ":", "")
	clean = strings.ReplaceAll(clean, "-", "")
	if len(clean) >= 4 {
		clean = clean[len(clean)-4:]
	} else {
		clean = "0000"
	}
	return SetupSSIDPrefix + strings.ToUpper(clean)
}
